# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
script:
  - make all
r_packages:
  ggplot2
  data.table
  dtplyr
  scales
  rmarkdown
  plotly
  jsonlite
  zoo
bioc_packages:
  BiocStyle
before_install:
  Rscript -e 'update.packages(ask = FALSE)'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: master
notifications:
  email:
    on_success: change
    on_failure: change
