# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
script:
  - make all
r_packages:
  ggplot2
  data.table
  dtplyr
  scales
  rmarkdown
  plotly
  jsonlite
  zoo
bioc_packages:
  BiocStyle

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
